namespace JameJam.HaftKhan;

/// <summary>A Haft Khan task: one labour on the to-do list.</summary>
/// <param name="Id">Stable identifier used by CLI commands.</param>
/// <param name="Title">What has to be done (sanitized, non-empty).</param>
/// <param name="Notes">Optional details (sanitized; empty when absent).</param>
/// <param name="Priority">Importance; higher sorts first.</param>
/// <param name="State">Lifecycle state.</param>
/// <param name="DueDate">Optional due date (day precision).</param>
/// <param name="CreatedAt">When the task was created (UTC).</param>
/// <param name="UpdatedAt">When the task was last modified (UTC).</param>
/// <param name="CompletedAt">When the task was completed (UTC); null while open.</param>
public sealed record HaftKhanTask(
    long Id,
    string Title,
    string Notes,
    TaskPriority Priority,
    TaskState State,
    DateOnly? DueDate,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? CompletedAt)
{
    /// <summary>Project the task belongs to (empty = none).</summary>
    public string Project { get; init; } = string.Empty;

    /// <summary>Tags attached to the task (never null).</summary>
    public IReadOnlyList<string> Tags { get; init; } = [];

    /// <summary>Estimated effort.</summary>
    public TaskEffort Effort { get; init; } = TaskEffort.None;

    /// <summary>Recurrence schedule (None = one-off).</summary>
    public RecurrenceKind Recurrence { get; init; } = RecurrenceKind.None;

    /// <summary>Recurrence interval (every N days/weeks/months).</summary>
    public int RecurrenceInterval { get; init; } = 1;

    /// <summary>When the task was last started (UTC); null if never started.</summary>
    public DateTimeOffset? StartedAt { get; init; }

    /// <summary>
    /// Stable identity used for syncing across devices. Generated at creation time and
    /// preserved by exports/imports — auto-increment ids are local-only.
    /// </summary>
    public string Uid { get; init; } = string.Empty;
}

/// <summary>A new task before it has been stored (no identity yet).</summary>
/// <param name="Title">What has to be done (already sanitized).</param>
/// <param name="Notes">Optional details (already sanitized; empty when absent).</param>
/// <param name="Priority">Importance.</param>
/// <param name="DueDate">Optional due date.</param>
public sealed record NewTask(
    string Title,
    string Notes,
    TaskPriority Priority,
    DateOnly? DueDate)
{
    /// <summary>Project the task belongs to (empty = none).</summary>
    public string Project { get; init; } = string.Empty;

    /// <summary>Tags to attach (already sanitized; never null).</summary>
    public IReadOnlyList<string> Tags { get; init; } = [];

    /// <summary>Estimated effort.</summary>
    public TaskEffort Effort { get; init; } = TaskEffort.None;

    /// <summary>Recurrence schedule.</summary>
    public RecurrenceKind Recurrence { get; init; } = RecurrenceKind.None;

    /// <summary>Recurrence interval (every N days/weeks/months).</summary>
    public int RecurrenceInterval { get; init; } = 1;

    /// <summary>Ids of tasks this one is blocked by (must exist when created).</summary>
    public IReadOnlyList<long> BlockedBy { get; init; } = [];

    /// <summary>Stable sync identity; generated by the store when null or empty.</summary>
    public string? Uid { get; init; }
}
